# Generated by Django 4.2 on 2026-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('profile_photo', models.FileField(upload_to='')),
            ],
        ),
    ]
